import type { LocalizationLocale } from './catalogs.js';

export const aiPlannerCatalogs = {
  en: {
    title: 'AI Planner',
    inputLabel: 'What do you want to plan?',
    inputPlaceholder: 'Add plans, times, places, or other details.',
    characterCounter: '{current}/{maximum}',
    attachImages: 'Add images',
    attachedImages: '{current} of {maximum} images attached',
    removeImage: 'Remove image',
    imageLimit: 'You can attach up to three images.',
    pickerFailed: 'Images could not be opened. Try again.',
    uploadFailed: 'An image could not be saved. Try again.',
    saveFailed: 'Your draft could not be saved. Try again.',
    localSaved: 'Draft saved on this device.',
    extractSchedule: 'Extract Schedule',
    extracting: 'Extracting schedule…',
    replaceDraftTitle: 'Replace current draft?',
    replaceDraftMessage: 'This will replace your current unconfirmed schedule.',
    replaceDraftAction: 'Replace',
    cancel: 'Cancel',
    partialImport: 'Some uncertain items were left out.',
    extractionFailed: 'The schedule could not be extracted. Try again.',
    confirmSchedule: 'Confirm Schedule',
    confirmScheduleTitle: 'Confirm schedule',
    confirmScheduleMessage:
      'Add this schedule to your calendar? This will activate {count} missions, schedule notifications, and sync with your connected calendar.',
    confirmationFailed: 'The schedule could not be activated. Try again.',
  },
  'zh-HK': {
    title: 'AI 規劃',
    inputLabel: '你想規劃甚麼？',
    inputPlaceholder: '加入行程、時間、地點或其他資料。',
    characterCounter: '{current}/{maximum}',
    attachImages: '加入圖片',
    attachedImages: '已加入 {current}/{maximum} 張圖片',
    removeImage: '移除圖片',
    imageLimit: '最多只可加入三張圖片。',
    pickerFailed: '未能開啟圖片，請再試一次。',
    uploadFailed: '未能儲存其中一張圖片，請再試一次。',
    saveFailed: '未能儲存草稿，請再試一次。',
    localSaved: '草稿已儲存在此裝置。',
    extractSchedule: '擷取行程',
    extracting: '正在擷取行程…',
    replaceDraftTitle: '取代目前草稿？',
    replaceDraftMessage: '這會取代你目前尚未確認的行程草稿。',
    replaceDraftAction: '取代',
    cancel: '取消',
    partialImport: '部分不確定的內容未有加入。',
    extractionFailed: '未能擷取行程，請再試一次。',
    confirmSchedule: '確認行程',
    confirmScheduleTitle: '確認行程',
    confirmScheduleMessage:
      '將這個行程加入日曆？這會啟用 {count} 個任務、安排通知，並與你已連接的日曆同步。',
    confirmationFailed: '未能啟用行程，請再試一次。',
  },
} as const satisfies Record<LocalizationLocale, Record<string, string>>;
