export const localizationCatalogs = {
  en: {
    'auth.signIn.title': 'Sign in to Misyra',
    'auth.signIn.apple': 'Continue with Apple',
    'auth.signIn.google': 'Continue with Google',
    'auth.signIn.failed': 'Sign-in failed. Please try again.',
    'onboarding.notifications.title': 'Mission reminders',
    'onboarding.notifications.body': 'Notifications can remind you when a mission starts.',
    'onboarding.notifications.enable': 'Enable notifications',
    'onboarding.notifications.notNow': 'Not now',
    'onboarding.calendar.title': 'Connect a calendar?',
    'onboarding.calendar.body':
      'Optionally connect one calendar. You can also do this later in Settings.',
    'onboarding.calendar.apple': 'Apple Calendar',
    'onboarding.calendar.google': 'Google Calendar',
    'onboarding.calendar.skip': 'Skip for now',
    'calendar.shell.title': 'Calendar',
    'calendar.shell.today': 'Today',
    'calendar.shell.levelPlaceholder': 'Level —',
    'calendar.shell.streakPlaceholder': 'Streak —',
    'calendar.shell.chooseDate': 'Choose date',
    'calendar.shell.close': 'Close',
    'calendar.shell.previousMonth': 'Previous month',
    'calendar.shell.nextMonth': 'Next month',
    'calendar.search.action': 'Search',
    'calendar.search.title': 'Search Calendar',
    'calendar.search.placeholder': 'Search missions',
    'calendar.search.noResults': 'No missions found.',
    'calendar.search.unavailable': 'This mission is no longer available.',
    'calendar.timeline.currentTime': 'Current time, {time}',
    'calendar.create.selectSlot': 'Select {time}',
    'calendar.create.title': 'New mission',
    'calendar.create.missionTitle': 'Mission title',
    'calendar.create.date': 'Date',
    'calendar.create.start': 'Start time',
    'calendar.create.end': 'End time',
    'calendar.create.moreOptions': 'More options',
    'calendar.create.recurrence': 'Recurrence',
    'calendar.create.doesNotRepeat': 'Does not repeat',
    'calendar.create.allDay': 'All day',
    'calendar.create.estimatedEffort': 'Estimated effort (minutes)',
    'calendar.create.timeZone': 'Time zone',
    'calendar.create.travelBehavior': 'When travelling',
    'calendar.create.keepLocalTime': 'Keep local time',
    'calendar.create.fixedInstant': 'Keep this instant',
    'calendar.create.private': 'Private / no evidence',
    'calendar.create.location': 'Location',
    'calendar.create.notes': 'Notes',
    'calendar.create.on': 'On',
    'calendar.create.off': 'Off',
    'calendar.create.validationError': 'Check the required mission fields before saving.',
    'calendar.create.pastZeroXpWarning':
      'Saving this mission in the past will permanently remove XP eligibility.',
    'calendar.edit.afterStartZeroXpWarning':
      'Editing after the start time will remove XP for this mission.',
    'calendar.adjustment.saved': 'Mission updated.',
    'calendar.adjustment.undo': 'Undo',
    'calendar.create.confirmZeroXp': 'Save with 0 XP',
    'calendar.create.cancel': 'Cancel',
    'calendar.create.save': 'Save',
    'calendar.details.title': 'Mission title',
    'calendar.details.schedule': 'Schedule',
    'calendar.details.location': 'Location',
    'calendar.details.notes': 'Notes',
    'calendar.details.personalNote': 'Personal note',
    'calendar.details.providerDescription': 'Organizer notes',
    'calendar.details.organizerControlled': 'Organizer-controlled',
    'calendar.details.duplicate': 'Duplicate',
    'calendar.details.delete': 'Delete',
    'calendar.details.status.future': 'Upcoming',
    'calendar.details.status.active': 'Active',
    'calendar.details.status.completed': 'Completed',
    'calendar.details.status.expired': 'Completion window expired',
    'calendar.details.status.cancelledOrganizer': 'Cancelled by organizer',
    'calendar.details.status.cancelled': 'Event cancelled',
    'calendar.details.evidence.notSubmitted': 'Evidence not submitted',
    'calendar.details.evidence.pending': 'Evidence under review',
    'calendar.details.evidence.accepted': 'Evidence accepted',
    'calendar.details.evidence.rejected': 'Evidence not accepted',
    'calendar.details.evidence.notRequired': 'No evidence required',
    'calendar.details.zeroXp.past': 'Created or moved into the past',
    'calendar.details.zeroXp.editedAfterStart': 'Edited after the start time',
    'calendar.allDay.more': '+{count} more',
    'calendar.mission.status.unfinished': 'Unfinished',
    'calendar.mission.status.verified': 'Accepted evidence, on time',
    'calendar.mission.status.late': 'Accepted late or self-confirmed',
    'calendar.mission.status.private': 'Private or Trust Mode completion',
    'sync.conflict.missionUpdated': 'This mission was updated on another device.',
    'sync.conflict.missionDeleted': 'This mission was deleted on another device.',
    'sync.conflict.missionCompletedElsewhere':
      'This mission was already completed on another device.',
    'sync.conflict.storyUpdated': 'This Story draft was updated on another device.',
  },
  'zh-HK': {
    'auth.signIn.title': '登入 Misyra',
    'auth.signIn.apple': '使用 Apple 繼續',
    'auth.signIn.google': '使用 Google 繼續',
    'auth.signIn.failed': '登入失敗，請再試一次。',
    'onboarding.notifications.title': '任務提醒',
    'onboarding.notifications.body': '通知可在任務開始時提醒你。',
    'onboarding.notifications.enable': '啟用通知',
    'onboarding.notifications.notNow': '暫時不要',
    'onboarding.calendar.title': '連接日曆？',
    'onboarding.calendar.body': '你可以選擇連接一個日曆，亦可稍後在設定中處理。',
    'onboarding.calendar.apple': 'Apple 日曆',
    'onboarding.calendar.google': 'Google 日曆',
    'onboarding.calendar.skip': '暫時略過',
    'calendar.shell.title': '日曆',
    'calendar.shell.today': '今天',
    'calendar.shell.levelPlaceholder': '等級 —',
    'calendar.shell.streakPlaceholder': '連續 —',
    'calendar.shell.chooseDate': '選擇日期',
    'calendar.shell.close': '關閉',
    'calendar.shell.previousMonth': '上個月',
    'calendar.shell.nextMonth': '下個月',
    'calendar.search.action': '搜尋',
    'calendar.search.title': '搜尋日曆',
    'calendar.search.placeholder': '搜尋任務',
    'calendar.search.noResults': '找不到任務。',
    'calendar.search.unavailable': '此任務已無法使用。',
    'calendar.timeline.currentTime': '目前時間，{time}',
    'calendar.create.selectSlot': '選擇 {time}',
    'calendar.create.title': '新增任務',
    'calendar.create.missionTitle': '任務名稱',
    'calendar.create.date': '日期',
    'calendar.create.start': '開始時間',
    'calendar.create.end': '結束時間',
    'calendar.create.moreOptions': '更多選項',
    'calendar.create.recurrence': '重複',
    'calendar.create.doesNotRepeat': '不重複',
    'calendar.create.allDay': '全日',
    'calendar.create.estimatedEffort': '預計投入時間（分鐘）',
    'calendar.create.timeZone': '時區',
    'calendar.create.travelBehavior': '旅行時',
    'calendar.create.keepLocalTime': '維持當地時間',
    'calendar.create.fixedInstant': '維持同一時刻',
    'calendar.create.private': '私人／毋須證據',
    'calendar.create.location': '地點',
    'calendar.create.notes': '備註',
    'calendar.create.on': '開啟',
    'calendar.create.off': '關閉',
    'calendar.create.validationError': '儲存前請檢查所有必填任務欄位。',
    'calendar.create.pastZeroXpWarning': '將任務儲存在過去時間會永久失去 XP 資格。',
    'calendar.edit.afterStartZeroXpWarning': '在開始時間後編輯會令此任務失去 XP。',
    'calendar.adjustment.saved': '任務已更新。',
    'calendar.adjustment.undo': '復原',
    'calendar.create.confirmZeroXp': '以 0 XP 儲存',
    'calendar.create.cancel': '取消',
    'calendar.create.save': '儲存',
    'calendar.details.title': '任務名稱',
    'calendar.details.schedule': '時間',
    'calendar.details.location': '地點',
    'calendar.details.notes': '備註',
    'calendar.details.personalNote': '私人任務備註',
    'calendar.details.providerDescription': '主辦者備註',
    'calendar.details.organizerControlled': '由主辦者控制',
    'calendar.details.duplicate': '複製',
    'calendar.details.delete': '刪除',
    'calendar.details.status.future': '即將開始',
    'calendar.details.status.active': '進行中',
    'calendar.details.status.completed': '已完成',
    'calendar.details.status.expired': '完成期限已過',
    'calendar.details.status.cancelledOrganizer': '已由主辦者取消',
    'calendar.details.status.cancelled': '活動已取消',
    'calendar.details.evidence.notSubmitted': '尚未提交證據',
    'calendar.details.evidence.pending': '證據審核中',
    'calendar.details.evidence.accepted': '證據已接納',
    'calendar.details.evidence.rejected': '證據未獲接納',
    'calendar.details.evidence.notRequired': '毋須證據',
    'calendar.details.zeroXp.past': '在過去時間建立或移動',
    'calendar.details.zeroXp.editedAfterStart': '在開始時間後編輯',
    'calendar.allDay.more': '另外 {count} 項',
    'calendar.mission.status.unfinished': '未完成',
    'calendar.mission.status.verified': '證據已接納，準時完成',
    'calendar.mission.status.late': '逾時完成或自行確認',
    'calendar.mission.status.private': '私人或信任模式完成',
    'sync.conflict.missionUpdated': '此任務已在另一部裝置上更新。',
    'sync.conflict.missionDeleted': '此任務已在另一部裝置上刪除。',
    'sync.conflict.missionCompletedElsewhere': '此任務已在另一部裝置上完成。',
    'sync.conflict.storyUpdated': '此 Story 草稿已在另一部裝置上更新。',
  },
} as const;

export type LocalizationLocale = keyof typeof localizationCatalogs;
export type LocalizationMessageKey = keyof (typeof localizationCatalogs)['en'];
