export const localizationCatalogs = {
  en: {
    'auth.signIn.title': 'Sign in to Misyra',
    'auth.signIn.apple': 'Continue with Apple',
    'auth.signIn.google': 'Continue with Google',
    'auth.signIn.failed': 'Sign-in failed. Please try again.',
    'onboarding.notifications.title': 'Mission reminders',
    'onboarding.notifications.body': 'Notifications can remind you when a mission starts.',
    'onboarding.notifications.enable': 'Enable notifications',
    'onboarding.notifications.notNow': 'Not now',
    'onboarding.calendar.title': 'Connect a calendar?',
    'onboarding.calendar.body':
      'Optionally connect one calendar. You can also do this later in Settings.',
    'onboarding.calendar.apple': 'Apple Calendar',
    'onboarding.calendar.google': 'Google Calendar',
    'onboarding.calendar.skip': 'Skip for now',
    'calendar.shell.title': 'Calendar',
    'calendar.shell.today': 'Today',
    'calendar.shell.levelPlaceholder': 'Level —',
    'calendar.shell.streakPlaceholder': 'Streak —',
    'calendar.shell.chooseDate': 'Choose date',
    'calendar.shell.close': 'Close',
    'calendar.shell.previousMonth': 'Previous month',
    'calendar.shell.nextMonth': 'Next month',
    'calendar.search.action': 'Search',
    'calendar.search.title': 'Search Calendar',
    'calendar.search.placeholder': 'Search missions',
    'calendar.search.noResults': 'No missions found.',
    'calendar.search.unavailable': 'This mission is no longer available.',
    'calendar.help.title': 'Calendar help',
    'calendar.help.dismiss': 'Dismiss Calendar help',
    'calendar.help.swipeToDismiss': 'Swipe down to dismiss Calendar help',
    'calendar.help.body':
      'Mission card colours show completion status. Written meanings are always available here.',
    'calendar.help.unfinished': 'Transparent — Unfinished',
    'calendar.help.verified': 'Green — Accepted evidence, on time',
    'calendar.help.late': 'Yellow — Accepted late or self-confirmed',
    'calendar.help.private': 'Grey — Private or Trust Mode completion',
    'calendar.help.recurring':
      'Repeating missions: when editing or deleting, choose this occurrence, this and future, or the entire series.',
    'calendar.help.gestures':
      'Tap a time slot twice to create. Drag or resize an unfinished mission card to change its time.',
    'calendar.help.completionTiming':
      'Completion opens at the scheduled start and stays available until 30 days after the scheduled finish. Submit evidence before expiry; evidence already submitted before expiry may finish verification afterward.',
    'calendar.help.faq': 'View full FAQ',
    'calendar.timeline.currentTime': 'Current time, {time}',
    'calendar.create.selectSlot': 'Select {time}',
    'calendar.create.title': 'New mission',
    'calendar.create.missionTitle': 'Mission title',
    'calendar.create.date': 'Date',
    'calendar.create.start': 'Start time',
    'calendar.create.end': 'End time',
    'calendar.create.timeInputHint': 'HH:MM',
    'calendar.create.moreOptions': 'More options',
    'calendar.create.recurrence': 'Recurrence',
    'calendar.create.doesNotRepeat': 'Does not repeat',
    'calendar.recurrence.title': 'Repeat',
    'calendar.recurrence.daily': 'Daily',
    'calendar.recurrence.weekly': 'Weekly',
    'calendar.recurrence.monthly': 'Monthly',
    'calendar.recurrence.yearly': 'Yearly',
    'calendar.recurrence.custom': 'Custom',
    'calendar.recurrence.sameDate': 'Same date',
    'calendar.recurrence.ordinalWeekday': 'Ordinal weekday',
    'calendar.recurrence.interval': 'Interval',
    'calendar.recurrence.month': 'Month',
    'calendar.recurrence.dayOfMonth': 'Day of month',
    'calendar.recurrence.ordinal.first': 'First',
    'calendar.recurrence.ordinal.second': 'Second',
    'calendar.recurrence.ordinal.third': 'Third',
    'calendar.recurrence.ordinal.fourth': 'Fourth',
    'calendar.recurrence.ordinal.last': 'Last',
    'calendar.recurrence.weekday.sun': 'Sun',
    'calendar.recurrence.weekday.mon': 'Mon',
    'calendar.recurrence.weekday.tue': 'Tue',
    'calendar.recurrence.weekday.wed': 'Wed',
    'calendar.recurrence.weekday.thu': 'Thu',
    'calendar.recurrence.weekday.fri': 'Fri',
    'calendar.recurrence.weekday.sat': 'Sat',
    'calendar.recurrence.ends': 'Ends',
    'calendar.recurrence.never': 'Never',
    'calendar.recurrence.onDate': 'On date',
    'calendar.recurrence.afterCount': 'After count',
    'calendar.recurrence.localDateInputHint': 'YYYY-MM-DD',
    'calendar.recurrence.done': 'Done',
    'calendar.create.allDay': 'All day',
    'calendar.create.estimatedEffort': 'Estimated effort (minutes)',
    'calendar.create.timeZone': 'Time zone',
    'calendar.create.travelBehavior': 'When travelling',
    'calendar.create.keepLocalTime': 'Keep local time',
    'calendar.create.fixedInstant': 'Keep this instant',
    'calendar.create.private': 'Private / no evidence',
    'calendar.create.location': 'Location',
    'calendar.create.notes': 'Notes',
    'calendar.create.on': 'On',
    'calendar.create.off': 'Off',
    'calendar.create.validationError': 'Check the required mission fields before saving.',
    'calendar.create.pastZeroXpWarning':
      'Saving this mission in the past will permanently remove XP eligibility.',
    'calendar.edit.afterStartZeroXpWarning':
      'Editing after the start time will remove XP for this mission.',
    'calendar.adjustment.saved': 'Mission updated.',
    'calendar.adjustment.undo': 'Undo',
    'calendar.create.confirmZeroXp': 'Save with 0 XP',
    'calendar.create.cancel': 'Cancel',
    'calendar.create.save': 'Save',
    'calendar.details.title': 'Mission title',
    'calendar.details.schedule': 'Schedule',
    'calendar.details.location': 'Location',
    'calendar.details.notes': 'Notes',
    'calendar.details.personalNote': 'Personal note',
    'calendar.details.providerDescription': 'Organizer notes',
    'calendar.details.organizerControlled': 'Organizer-controlled',
    'calendar.details.recurringEditPending':
      'Recurring mission edits use recurrence scope controls.',
    'calendar.details.save': 'Save changes',
    'calendar.details.duplicate': 'Duplicate',
    'calendar.details.delete': 'Delete',
    'calendar.recurringScope.editTitle': 'Edit repeating mission',
    'calendar.recurringScope.deleteTitle': 'Delete repeating mission',
    'calendar.recurringScope.restoreTitle': 'Restore repeating event',
    'calendar.recurringScope.thisOccurrence': 'This occurrence',
    'calendar.recurringScope.thisAndFuture': 'This and future occurrences',
    'calendar.recurringScope.entireSeries': 'Entire series',
    'calendar.recurringScope.cancel': 'Cancel',
    'calendar.details.status.future': 'Upcoming',
    'calendar.details.status.active': 'Active',
    'calendar.details.status.completed': 'Completed',
    'calendar.details.status.expired': 'Completion window expired',
    'calendar.details.status.cancelledOrganizer': 'Cancelled by organizer',
    'calendar.details.status.cancelled': 'Event cancelled',
    'calendar.details.evidence.notSubmitted': 'Evidence not submitted',
    'calendar.details.evidence.pending': 'Evidence under review',
    'calendar.details.evidence.accepted': 'Evidence accepted',
    'calendar.details.evidence.rejected': 'Evidence not accepted',
    'calendar.details.evidence.notRequired': 'No evidence required',
    'calendar.details.zeroXp.past': 'Created or moved into the past',
    'calendar.details.zeroXp.editedAfterStart': 'Edited after the start time',
    'calendar.allDay.more': '+{count} more',
    'calendar.mission.status.unfinished': 'Unfinished',
    'calendar.mission.status.verified': 'Accepted evidence, on time',
    'calendar.mission.status.late': 'Accepted late or self-confirmed',
    'calendar.mission.status.private': 'Private or Trust Mode completion',
    'sync.conflict.missionUpdated': 'This mission was updated on another device.',
    'sync.conflict.missionDeleted': 'This mission was deleted on another device.',
    'sync.conflict.missionCompletedElsewhere':
      'This mission was already completed on another device.',
    'sync.conflict.storyUpdated': 'This Story draft was updated on another device.',
    'evidence.close': 'Close',
    'evidence.permission.title': 'Camera access is required',
    'evidence.permission.body': 'Use the camera to capture evidence for this mission.',
    'evidence.permission.openSettings': 'Open Settings',
    'evidence.capture': 'Take photo',
    'evidence.retake': 'Retake',
    'evidence.submit': 'Submit Evidence',
    'evidence.manage': 'Manage evidence',
    'evidence.media.saveToPhotos': 'Save to Photos',
    'evidence.media.delete': 'Delete evidence',
    'evidence.captureFailed': 'Could not capture evidence. Try again.',
    'evidence.result.waiting': 'Waiting for verification',
    'evidence.result.accepted': 'Evidence accepted',
    'evidence.result.rejected': 'Evidence not accepted',
    'evidence.result.expired': 'Completion window expired',
    'evidence.result.tryAnotherPhoto': 'Try another photo',
    'evidence.result.selfConfirm': 'I completed this mission',
    'evidence.result.selfConfirmPrompt': 'Mark completed?',
    'evidence.result.confirmSelfCompletion': 'Mark completed',
    'evidence.result.cancel': 'Cancel',
    'evidence.result.remainingAttempts': '{count} evidence attempts remaining',
    'evidence.result.reason.taskMismatch': 'The photo does not match this mission.',
    'evidence.result.reason.taskNotEvident': 'The mission is not clear in the photo.',
    'evidence.result.reason.imageUnusable': 'The photo could not be checked.',
    'story.editor.title': 'Story',
    'story.editor.close': 'Close',
    'story.editor.save': 'Save',
    'story.editor.source': 'Source photo',
    'story.editor.sourcePhoto': 'Photo {number}',
    'story.editor.undo': 'Undo',
    'story.editor.redo': 'Redo',
    'story.editor.zoomIn': 'Zoom in',
    'story.editor.zoomOut': 'Zoom out',
    'story.editor.moveLeft': 'Left',
    'story.editor.moveRight': 'Right',
    'story.editor.moveUp': 'Up',
    'story.editor.moveDown': 'Down',
    'story.editor.headline': 'Headline',
    'story.editor.supportingText': 'Supporting text',
    'story.editor.editHeadline': 'Edit headline',
    'story.editor.editSupportingText': 'Edit supporting text',
    'story.editor.textSmaller': 'Text smaller',
    'story.editor.textLarger': 'Text larger',
    'story.editor.textColor': 'Text colour',
    'story.editor.font': 'Font',
    'story.editor.removeText': 'Remove text',
    'story.editor.contrast': 'Contrast',
    'story.editor.remainingGenerations': '{count} AI generations remaining',
    'story.editor.versions': 'Versions',
    'story.editor.versionSource': 'Source',
    'story.editor.versionGenerated': 'AI {number}',
    'story.editor.generateVersion': 'Generate AI version',
    'story.editor.deleteVersion': 'Delete version',
    'story.suggestions.title': 'Suggestions',
    'story.suggestions.useHeadline': 'Use headline',
    'story.suggestions.useSupportingText': 'Use supporting text',
    'story.suggestions.useBoth': 'Use both',
    'story.suggestions.photoOnly': 'Photo only',
    'story.suggestions.sharingNotes': 'Sharing Notes',
    'story.suggestions.musicMood': 'Music / mood',
    'story.suggestions.mention': 'Mention',
    'story.suggestions.location': 'Location',
    'story.suggestions.poll': 'Poll',
    'story.styleProfile.title': 'Story style profile',
    'story.styleProfile.settings': 'Story style profile',
    'story.styleProfile.manage': 'Manage Story style',
    'story.styleProfile.body':
      'Choose 3–8 reference images. Misyra keeps only abstract style traits, not exact templates or identity details.',
    'story.styleProfile.setup': 'Set up my style',
    'story.styleProfile.useDefault': 'Use default',
    'story.styleProfile.replaceReferences': 'Add or replace references',
    'story.styleProfile.rebuild': 'Build style from references',
    'story.styleProfile.resetDefault': 'Reset to default',
    'story.styleProfile.selectedCount': '{count} references selected',
    'story.styleProfile.referenceLimit': 'Choose between 3 and 8 reference images.',
    'story.styleProfile.networkRequired': 'An internet connection is required to build your style.',
    'story.styleProfile.statusUnset': 'Style not set up',
    'story.styleProfile.statusDefault': 'Using default style',
    'story.styleProfile.statusCustom': 'Custom style active',
  },
  'zh-HK': {
    'auth.signIn.title': '登入 Misyra',
    'auth.signIn.apple': '使用 Apple 繼續',
    'auth.signIn.google': '使用 Google 繼續',
    'auth.signIn.failed': '登入失敗，請再試一次。',
    'onboarding.notifications.title': '任務提醒',
    'onboarding.notifications.body': '通知可在任務開始時提醒你。',
    'onboarding.notifications.enable': '啟用通知',
    'onboarding.notifications.notNow': '暫時不要',
    'onboarding.calendar.title': '連接日曆？',
    'onboarding.calendar.body': '你可以選擇連接一個日曆，亦可稍後在設定中處理。',
    'onboarding.calendar.apple': 'Apple 日曆',
    'onboarding.calendar.google': 'Google 日曆',
    'onboarding.calendar.skip': '暫時略過',
    'calendar.shell.title': '日曆',
    'calendar.shell.today': '今天',
    'calendar.shell.levelPlaceholder': '等級 —',
    'calendar.shell.streakPlaceholder': '連續 —',
    'calendar.shell.chooseDate': '選擇日期',
    'calendar.shell.close': '關閉',
    'calendar.shell.previousMonth': '上個月',
    'calendar.shell.nextMonth': '下個月',
    'calendar.search.action': '搜尋',
    'calendar.search.title': '搜尋日曆',
    'calendar.search.placeholder': '搜尋任務',
    'calendar.search.noResults': '找不到任務。',
    'calendar.search.unavailable': '此任務已無法使用。',
    'calendar.help.title': '日曆說明',
    'calendar.help.dismiss': '關閉日曆說明',
    'calendar.help.swipeToDismiss': '向下滑動以關閉日曆說明',
    'calendar.help.body': '任務卡顏色顯示完成狀態；以下文字說明會一直提供。',
    'calendar.help.unfinished': '透明 — 未完成',
    'calendar.help.verified': '綠色 — 證據已接納，準時完成',
    'calendar.help.late': '黃色 — 逾時完成或自行確認',
    'calendar.help.private': '灰色 — 私人或信任模式完成',
    'calendar.help.recurring': '重複任務：編輯或刪除時可選擇只改今次、今次及之後，或整個系列。',
    'calendar.help.gestures': '連按時間位置兩次可建立任務。拖動或調整任務卡大小可更改時間。',
    'calendar.help.completionTiming':
      '任務到預定開始時間即可完成，並於預定結束時間後 30 日到期。證據須在到期前提交；已在到期前提交的證據可在到期後完成驗證。',
    'calendar.help.faq': '查看完整常見問題',
    'calendar.timeline.currentTime': '目前時間，{time}',
    'calendar.create.selectSlot': '選擇 {time}',
    'calendar.create.title': '新增任務',
    'calendar.create.missionTitle': '任務名稱',
    'calendar.create.date': '日期',
    'calendar.create.start': '開始時間',
    'calendar.create.end': '結束時間',
    'calendar.create.timeInputHint': '時:分',
    'calendar.create.moreOptions': '更多選項',
    'calendar.create.recurrence': '重複',
    'calendar.create.doesNotRepeat': '不重複',
    'calendar.recurrence.title': '重複',
    'calendar.recurrence.daily': '每日',
    'calendar.recurrence.weekly': '每週',
    'calendar.recurrence.monthly': '每月',
    'calendar.recurrence.yearly': '每年',
    'calendar.recurrence.custom': '自訂',
    'calendar.recurrence.sameDate': '同一日期',
    'calendar.recurrence.ordinalWeekday': '第幾個星期幾',
    'calendar.recurrence.interval': '間隔',
    'calendar.recurrence.month': '月份',
    'calendar.recurrence.dayOfMonth': '日期',
    'calendar.recurrence.ordinal.first': '第一個',
    'calendar.recurrence.ordinal.second': '第二個',
    'calendar.recurrence.ordinal.third': '第三個',
    'calendar.recurrence.ordinal.fourth': '第四個',
    'calendar.recurrence.ordinal.last': '最後一個',
    'calendar.recurrence.weekday.sun': '日',
    'calendar.recurrence.weekday.mon': '一',
    'calendar.recurrence.weekday.tue': '二',
    'calendar.recurrence.weekday.wed': '三',
    'calendar.recurrence.weekday.thu': '四',
    'calendar.recurrence.weekday.fri': '五',
    'calendar.recurrence.weekday.sat': '六',
    'calendar.recurrence.ends': '結束',
    'calendar.recurrence.never': '永不',
    'calendar.recurrence.onDate': '於日期',
    'calendar.recurrence.afterCount': '完成次數後',
    'calendar.recurrence.localDateInputHint': '年-月-日',
    'calendar.recurrence.done': '完成',
    'calendar.create.allDay': '全日',
    'calendar.create.estimatedEffort': '預計投入時間（分鐘）',
    'calendar.create.timeZone': '時區',
    'calendar.create.travelBehavior': '旅行時',
    'calendar.create.keepLocalTime': '維持當地時間',
    'calendar.create.fixedInstant': '維持同一時刻',
    'calendar.create.private': '私人／毋須證據',
    'calendar.create.location': '地點',
    'calendar.create.notes': '備註',
    'calendar.create.on': '開啟',
    'calendar.create.off': '關閉',
    'calendar.create.validationError': '儲存前請檢查所有必填任務欄位。',
    'calendar.create.pastZeroXpWarning': '將任務儲存在過去時間會永久失去 XP 資格。',
    'calendar.edit.afterStartZeroXpWarning': '在開始時間後編輯會令此任務失去 XP。',
    'calendar.adjustment.saved': '任務已更新。',
    'calendar.adjustment.undo': '復原',
    'calendar.create.confirmZeroXp': '以 0 XP 儲存',
    'calendar.create.cancel': '取消',
    'calendar.create.save': '儲存',
    'calendar.details.title': '任務名稱',
    'calendar.details.schedule': '時間',
    'calendar.details.location': '地點',
    'calendar.details.notes': '備註',
    'calendar.details.personalNote': '私人任務備註',
    'calendar.details.providerDescription': '主辦者備註',
    'calendar.details.organizerControlled': '由主辦者控制',
    'calendar.details.recurringEditPending': '重複任務編輯會使用重複範圍控制。',
    'calendar.details.save': '儲存變更',
    'calendar.details.duplicate': '複製',
    'calendar.details.delete': '刪除',
    'calendar.recurringScope.editTitle': '編輯重複任務',
    'calendar.recurringScope.deleteTitle': '刪除重複任務',
    'calendar.recurringScope.restoreTitle': '還原重複行程',
    'calendar.recurringScope.thisOccurrence': '只限今次',
    'calendar.recurringScope.thisAndFuture': '今次及之後',
    'calendar.recurringScope.entireSeries': '整個系列',
    'calendar.recurringScope.cancel': '取消',
    'calendar.details.status.future': '即將開始',
    'calendar.details.status.active': '進行中',
    'calendar.details.status.completed': '已完成',
    'calendar.details.status.expired': '完成期限已過',
    'calendar.details.status.cancelledOrganizer': '已由主辦者取消',
    'calendar.details.status.cancelled': '活動已取消',
    'calendar.details.evidence.notSubmitted': '尚未提交證據',
    'calendar.details.evidence.pending': '證據審核中',
    'calendar.details.evidence.accepted': '證據已接納',
    'calendar.details.evidence.rejected': '證據未獲接納',
    'calendar.details.evidence.notRequired': '毋須證據',
    'calendar.details.zeroXp.past': '在過去時間建立或移動',
    'calendar.details.zeroXp.editedAfterStart': '在開始時間後編輯',
    'calendar.allDay.more': '另外 {count} 項',
    'calendar.mission.status.unfinished': '未完成',
    'calendar.mission.status.verified': '證據已接納，準時完成',
    'calendar.mission.status.late': '逾時完成或自行確認',
    'calendar.mission.status.private': '私人或信任模式完成',
    'sync.conflict.missionUpdated': '此任務已在另一部裝置上更新。',
    'sync.conflict.missionDeleted': '此任務已在另一部裝置上刪除。',
    'sync.conflict.missionCompletedElsewhere': '此任務已在另一部裝置上完成。',
    'sync.conflict.storyUpdated': '此 Story 草稿已在另一部裝置上更新。',
    'evidence.close': '關閉',
    'evidence.permission.title': '需要相機權限',
    'evidence.permission.body': '使用相機拍攝此任務的證據。',
    'evidence.permission.openSettings': '開啟設定',
    'evidence.capture': '拍照',
    'evidence.retake': '重拍',
    'evidence.submit': '提交證據',
    'evidence.manage': '管理證據',
    'evidence.media.saveToPhotos': '儲存到相片',
    'evidence.media.delete': '刪除證據',
    'evidence.captureFailed': '無法拍攝證據，請再試一次。',
    'evidence.result.waiting': '等待驗證',
    'evidence.result.accepted': '證據已接納',
    'evidence.result.rejected': '證據未獲接納',
    'evidence.result.expired': '完成期限已過',
    'evidence.result.tryAnotherPhoto': '再拍一張',
    'evidence.result.selfConfirm': '我已完成此任務',
    'evidence.result.selfConfirmPrompt': '標記為已完成？',
    'evidence.result.confirmSelfCompletion': '標記已完成',
    'evidence.result.cancel': '取消',
    'evidence.result.remainingAttempts': '剩餘 {count} 次證據提交機會',
    'evidence.result.reason.taskMismatch': '相片內容與此任務不相符。',
    'evidence.result.reason.taskNotEvident': '相片未能清楚顯示任務已完成。',
    'evidence.result.reason.imageUnusable': '無法檢查此相片。',
    'story.editor.title': 'Story',
    'story.editor.close': '關閉',
    'story.editor.save': '儲存',
    'story.editor.source': '來源相片',
    'story.editor.sourcePhoto': '相片 {number}',
    'story.editor.undo': '復原',
    'story.editor.redo': '重做',
    'story.editor.zoomIn': '放大',
    'story.editor.zoomOut': '縮小',
    'story.editor.moveLeft': '向左',
    'story.editor.moveRight': '向右',
    'story.editor.moveUp': '向上',
    'story.editor.moveDown': '向下',
    'story.editor.headline': '標題',
    'story.editor.supportingText': '補充文字',
    'story.editor.editHeadline': '編輯標題',
    'story.editor.editSupportingText': '編輯補充文字',
    'story.editor.textSmaller': '縮小文字',
    'story.editor.textLarger': '放大文字',
    'story.editor.textColor': '文字顏色',
    'story.editor.font': '字體',
    'story.editor.removeText': '移除文字',
    'story.editor.contrast': '對比',
    'story.editor.remainingGenerations': '剩餘 {count} 次 AI 生成機會',
    'story.editor.versions': '版本',
    'story.editor.versionSource': '來源',
    'story.editor.versionGenerated': 'AI {number}',
    'story.editor.generateVersion': '生成 AI 版本',
    'story.editor.deleteVersion': '刪除版本',
    'story.suggestions.title': '建議',
    'story.suggestions.useHeadline': '使用標題',
    'story.suggestions.useSupportingText': '使用補充文字',
    'story.suggestions.useBoth': '兩者都使用',
    'story.suggestions.photoOnly': '只用相片',
    'story.suggestions.sharingNotes': '分享備註',
    'story.suggestions.musicMood': '音樂／氣氛',
    'story.suggestions.mention': '提及帳戶',
    'story.suggestions.location': '地點',
    'story.suggestions.poll': '投票',
    'story.styleProfile.title': 'Story 風格設定',
    'story.styleProfile.settings': 'Story 風格設定',
    'story.styleProfile.manage': '管理 Story 風格',
    'story.styleProfile.body':
      '選擇 3–8 張參考圖片。Misyra 只會保留抽象風格特徵，不會複製完整範本或身份資料。',
    'story.styleProfile.setup': '設定我的風格',
    'story.styleProfile.useDefault': '使用預設',
    'story.styleProfile.replaceReferences': '新增或更換參考圖片',
    'story.styleProfile.rebuild': '根據參考圖片建立風格',
    'story.styleProfile.resetDefault': '重設為預設',
    'story.styleProfile.selectedCount': '已選擇 {count} 張參考圖片',
    'story.styleProfile.referenceLimit': '請選擇 3 至 8 張參考圖片。',
    'story.styleProfile.networkRequired': '建立風格時需要網絡連線。',
    'story.styleProfile.statusUnset': '尚未設定風格',
    'story.styleProfile.statusDefault': '正在使用預設風格',
    'story.styleProfile.statusCustom': '自訂風格已啟用',
  },
} as const;

export type LocalizationLocale = keyof typeof localizationCatalogs;
export type LocalizationMessageKey = keyof (typeof localizationCatalogs)['en'];
